drop table if exists t_image CASCADE ;
drop table if exists t_scrap CASCADE ;
create table t_image (image_id bigint generated by default as identity, create_at timestamp, update_at timestamp, download_try_cnt integer, height integer, is_downloaded boolean, local_path varchar(255), mime_type varchar(255), url varchar(255), width integer, primary key (image_id));
create table t_scrap (scrap_id bigint generated by default as identity, create_at timestamp, update_at timestamp, description varchar(255), title varchar(255), user_id bigint, view_cnt bigint, image_id bigint, primary key (scrap_id));
alter table t_scrap add constraint FKjmsdcbsjf356uvy8x77mi0vd6 foreign key (image_id) references t_image;